version: 2

sources:

  # --------------------------
  # Users table (raw)
  # --------------------------
  - name: users
    description: "Raw users table from public schema"
    database: ecosave_local          #  actual database
    schema: public
    tables:
      - name: users
        description: "User master data"

  # --------------------------
  # Leads table (raw)
  # --------------------------
  - name: lead
    description: "Raw leads table from public schema"
    database: ecosave_local
    schema: public
    tables:
      - name: lead
        description: "All leads coming from suppliers"

  # --------------------------
  # History / Calls table (raw)
  # --------------------------
  - name: history
    description: "Raw call history table from public schema"
    database: ecosave_local
    schema: public
    tables:
      - name: history
        description: "Call history for all leads"

  # --------------------------
  # Campaigns table (raw)
  # --------------------------
  - name: campaign
    description: "Raw campaign table from public schema"
    database: ecosave_local
    schema: public
    tables:
      - name: campaign
        description: "Campaign master data"

  # --------------------------
  # Lists table (raw)
  # --------------------------
  - name: list
    description: "Raw list table from public schema"
    database: ecosave_local
    schema: public
    tables:
      - name: list
        description: "Lead lists information"

  # --------------------------
  # suppliers table (raw)
  # --------------------------
  - name: import_supplier
    description: "Raw supplier table from public schema"
    database: ecosave_local
    schema: public
    tables:
      - name: import_supplier
        description: "supplier information"

  # --------------------------
  # result code table (raw)
  # --------------------------
  - name: result_code
    description: "Raw result code table from public schema"
    database: ecosave_local
    schema: public
    tables:
      - name: result_code
        description: "result code information"

  # --------------------------
  # result code  Mapping table (raw)
  # --------------------------
  - name: result_code_mapping
    schema: analytics
    tables:
      - name: result_code_mapping


  - name: client_meters
    description: "details "
    database: ecosave_local
    schema: raw
    tables:
      - name: client_meters
        description: "result code information"

  - name: clients
    description: "details "
    database: ecosave_local
    schema: raw
    tables:
      - name: clients
        description: "result code information"
  - name: client_status
    description: "details "
    database: ecosave_local
    schema: raw
    tables:
      - name: client_status
        description: "result code information"
  - name: company
    description: "details "
    database: ecosave_local
    schema: raw
    tables:
      - name: company
        description: "result code information"

  - name: active_users
    description: "details "
    database: ecosave_local
    schema: raw
    tables:
      - name: active_users
        description: "result code information"

  - name: tracker_main_data
    description: "details "
    database: ecosave_local
    schema: raw
    tables:
      - name: tracker_main_data
        description: "result code information"

  - name: fct_calls
    description: "details "
    database: ecosave_local
    schema: public
    tables:
      - name: fct_calls
        description: "result code information"

  - name: client_meters_field_history
    description: "details "
    database: ecosave_local
    schema: raw
    tables:
      - name: client_meters_field_history
        description: "result code information"

  - name: monthly_breakdown
    description: "details "
    database: ecosave_local
    schema: public
    tables:
      - name: monthly_breakdown
        description: "result code information"

  - name: eazi_users
    description: "details "
    database: ecosave_local
    schema: raw
    tables:
      - name: users
        description: "result code information"

  - name: supplier_status_mapping
    description: "details "
    database: ecosave_local
    schema: raw
    tables:
      - name: supplier_status_mapping
        description: "result code information"
      



  