version: 2

sources:

  # --------------------------
  # Users table (raw)
  # --------------------------
  - name: users
    description: "Raw users (agents) table from maxcontact"
    database: ecosave_local          #  actual database
    schema: public
    tables:
      - name: users
        description: "User master data"

  # --------------------------
  # Leads table (raw)
  # --------------------------
  - name: lead
    description: "Raw leads table from maxcontact- refreshed daily"
    database: ecosave_local
    schema: public
    tables:
      - name: lead
        description: "All leads present in lead table"

  # --------------------------
  # History / Calls table (raw)
  # --------------------------
  - name: history
    description: "Raw call history table from max contact"
    database: ecosave_local
    schema: public
    tables:
      - name: history
        description: "Call history for all leads"

  # --------------------------
  # Campaigns table (raw)
  # --------------------------
  - name: campaign
    description: "Raw campaign table from maxcontact"
    database: ecosave_local
    schema: public
    tables:
      - name: campaign
        description: "Campaign master data"

  # --------------------------
  # Lists table (raw)
  # --------------------------
  - name: list
    description: "Raw list table from maxcontact"
    database: ecosave_local
    schema: public
    tables:
      - name: list
        description: "Lead lists information"

  # --------------------------
  # suppliers table (raw)
  # --------------------------
  - name: import_supplier
    description: "Raw Data-supplier table from public schema"
    database: ecosave_local
    schema: public
    tables:
      - name: import_supplier
        description: "supplier information"

  # --------------------------
  # result code table (raw)
  # --------------------------
  - name: result_code
    description: "Raw result code table from maxcontact"
    database: ecosave_local
    schema: public
    tables:
      - name: result_code
        description: "result code information"

  # --------------------------
  # result code  Mapping table (raw)
  # --------------------------
  - name: result_code_mapping
    description:  "mapping table used to map result codes into outcome buckets and also add is_contacted flag for making human contact"
    schema: analytics
    tables:
      - name: result_code_mapping


  - name: client_meters
    description: "client meters table from EAZI refreshed daily "
    database: ecosave_local
    schema: raw
    tables:
      - name: client_meters
        description: "client meters table "

  - name: clients
    description: "clients table from EAZI refershed daily "
    database: ecosave_local
    schema: raw
    tables:
      - name: clients
        description: "result code information"
  - name: client_status
    description: "client_status table from EAZI refreshed daily"
    database: ecosave_local
    schema: raw
    tables:
      - name: client_status
        description: "client status from "
  - name: company
    description: "energy supplier companies from EAZI CRM "
    database: ecosave_local
    schema: raw
    tables:
      - name: company
        description: Company information"

  - name: active_users
    description: "active users"
    database: ecosave_local
    schema: raw
    tables:
      - name: active_users
        description: "result code information"

  - name: tracker_main_data
    description: "Sold meters from EAZI"
    database: ecosave_local
    schema: raw
    tables:
      - name: tracker_main_data
        description: "Sold meters"

  - name: fct_calls
    description: "call history mart table"
    database: ecosave_local
    schema: public
    tables:
      - name: fct_calls
        description: "call history"

  - name: client_meters_field_history
    description: "changes in client_meters table "
    database: ecosave_local
    schema: raw
    tables:
      - name: client_meters_field_history
        description: "incrementally refreshed daily"

  - name: monthly_breakdown
    description: "Derived table from python code"
    database: ecosave_local
    schema: public
    tables:
      - name: monthly_breakdown
        description: "derived table to see opportunities"

  - name: eazi_users
    description: "user data from EAZI"
    database: ecosave_local
    schema: raw
    tables:
      - name: users
        description: "user data from EAZI"

  
  - name: client_status
    description: "client status from EAZI"
    database: ecosave_local
    schema: raw
    tables:
      - name: client_status
        description: "client status"

  
      



  